### ISSUE TITLE
Question about building

### ISSUE THREAD

**Issue by griz1112** [OpenSolo/solo-builder#3]
Totally confused with the vagrant system. I can build the firmware it boots up no problem but where is the source so I can try some changes? Do you just git all the other repos into your solo-builder directory so you can see them in the vm? Sorry all I had when I was writing code was make and configure :) This is all kinda strange to me.

**Comment by peterbarker** [comment]
On Fri, 11 Aug 2017, Dan Pollock wrote:

> Totally confused with the vagrant system. I can build the firmware it boots
> up no problem but where is the source so I can try some changes? Do you just
> git all the other repos into your solo-builder directory so you can see them
> in the vm? Sorry all I had when I was writing code was make and configure :)
> This is all kinda strange to me.

Ordinarily it is a little interesting to get bitbake and repo to source 
stuff from different places for you.

The good news is that Matt has done some work to simplify the process, 
present in this PR: https://github.com/OpenSolo/solo-builder/pull/2/files

Are you in a position to test that PR?

**Comment by griz1112** [comment]
Yep I can give it a go in a bit.

**Comment by griz1112** [comment]
It built the two SD images and all the other files ok. Can't test the image I am waiting on a controller. Used linux to build with The tablet that I have windows on is waiting on a new battery. Everything else is linux. What I need to be able to do is put the controller image on a imx6 card and log into it via wifi without having the artoo controller. So I only need to edit some config files before its built for my base image.

**Comment by griz1112** [comment]
Built a custom image with it today boots up fine.
